// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHUUw711sXtxi3YH_7ikLsWFFhrLBmrRE',
    appId: '1:832023030442:web:7db3bcda8e8466989dfed3',
    messagingSenderId: '832023030442',
    projectId: 'abs6-816d7',
    authDomain: 'abs6-816d7.firebaseapp.com',
    databaseURL: 'https://abs6-816d7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'abs6-816d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bYH07pgYmSTrktfUHxHO0brArp7aHEo',
    appId: '1:832023030442:android:8d7e8f0e9e13a6389dfed3',
    messagingSenderId: '832023030442',
    projectId: 'abs6-816d7',
    databaseURL: 'https://abs6-816d7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'abs6-816d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ2XUhFubiiZeWNnk652Qga50SNpITrzs',
    appId: '1:832023030442:ios:7224fc1ba91334ce9dfed3',
    messagingSenderId: '832023030442',
    projectId: 'abs6-816d7',
    databaseURL: 'https://abs6-816d7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'abs6-816d7.appspot.com',
    iosClientId: '832023030442-1hkcqhscps1ijjpa438ale7f4950o6e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ2XUhFubiiZeWNnk652Qga50SNpITrzs',
    appId: '1:832023030442:ios:7224fc1ba91334ce9dfed3',
    messagingSenderId: '832023030442',
    projectId: 'abs6-816d7',
    databaseURL: 'https://abs6-816d7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'abs6-816d7.appspot.com',
    iosClientId: '832023030442-1hkcqhscps1ijjpa438ale7f4950o6e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.namerApp',
  );
}
