name: easy_calendar3
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  cloud_firestore: ^4.5.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cupertino_icons: ^1.0.2
  firebase_auth_web: ^5.3.0
  table_calendar: ^3.0.8
  intl: ^0.17.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  
  assets:
     - assets/images/Scheduling-image.png


  fonts:
     - family: Hind
       fonts:
         - asset: assets/fonts/Hind-bold.ttf
         - asset:  assets/fonts/Hind-regular.ttf
